CREATE USER libman WITH
  LOGIN
  SUPERUSER
  CREATEDB
  CREATEROLE
  INHERIT
  NOREPLICATION
  CONNECTION LIMIT -1
  PASSWORD '745180aA';

CREATE DATABASE library WITH OWNER = libman CONNECTION LIMIT = -1;
